// СГЕНЕРИРОВАНО: python scripts/build-palette.py --ts
// Правьте палитру в src/index.css и перегенерируйте — руками этот
// файл не редактируется. `figma: null` — имя выведено по правилу
// контраста, а не взято из набора Figma.

export interface PaletteColor {
  /** Имя CSS-переменной без `--`, как в Figma. */
  name: string
  family: string
  /** Значение в теме ЕЛК; живое значение история читает из CSS. */
  hex: string
  /** Имя переменной в наборе Figma; null — выведено. */
  figma: string | null
  /** Семантические токены, которые на неё ссылаются. */
  usedBy: string[]
}

export const PALETTE: PaletteColor[] = [
  {
    name: "blue-104",
    family: "blue",
    hex: "#F0FCFF",
    figma: null,
    usedBy: ["pagination-hover-bg", "mail-feed-new-bg"],
  },
  {
    name: "blue-114",
    family: "blue",
    hex: "#CFF7FF",
    figma: "Second/Blue colors/Blue 114",
    usedBy: ["menu-banner-blue-glow", "pagination-active-bg"],
  },
  {
    name: "blue-121",
    family: "blue",
    hex: "#B6F3FF",
    figma: "Second/Blue colors/Blue 121",
    usedBy: ["toggle-track-checked-bg-disabled", "menu-banner-blue-bg", "pagination-onclick-bg"],
  },
  {
    name: "blue-223",
    family: "blue",
    hex: "#80E3FF",
    figma: "Base/Blue 223",
    usedBy: ["btn-primary-bg", "loader-fg", "checkbox-checked-bg", "radio-checked-bg", "toggle-track-checked-bg", "range-input-accent", "steps-active-ring", "filter-active-border", "autocomplete-match-bg"],
  },
  {
    name: "blue-187",
    family: "blue",
    hex: "#2FCEEF",
    figma: "Second/Blue colors/Blue 187",
    usedBy: ["btn-primary-bg-hover", "checkbox-checked-bg-hover", "radio-checked-bg-hover", "toggle-track-checked-bg-hover", "range-input-indicator-bg", "file-item-loading-fg", "progress-step-fill"],
  },
  {
    name: "blue-254",
    family: "blue",
    hex: "#14B1D1",
    figma: "Second/Blue colors/Blue 254",
    usedBy: ["btn-primary-bg-active", "calendar-accent-fg", "header-hover-fg", "header-check-fg", "item-check-fg"],
  },
  {
    name: "dark-blue-109",
    family: "dark-blue",
    hex: "#EDF6FC",
    figma: "Second/Dark blue colors/Dark blue 109",
    usedBy: ["top-fixed-message-blue-bg", "tag-blue-secondary-bg"],
  },
  {
    name: "dark-blue-117",
    family: "dark-blue",
    hex: "#E3EEFF",
    figma: null,
    usedBy: [],
  },
  {
    name: "dark-blue-322",
    family: "dark-blue",
    hex: "#5B90E0",
    figma: null,
    usedBy: ["top-fixed-message-blue-icon"],
  },
  {
    name: "dark-blue-389",
    family: "dark-blue",
    hex: "#2487CA",
    figma: "Status/Dark blue 389",
    usedBy: ["tag-blue-bg"],
  },
  {
    name: "dark-blue-596",
    family: "dark-blue",
    hex: "#1368A1",
    figma: "Second/Dark blue colors/Dark blue 596",
    usedBy: ["btn-secondary-black-bg-active"],
  },
  {
    name: "dark-blue-701",
    family: "dark-blue",
    hex: "#0D4CD3",
    figma: null,
    usedBy: ["btn-secondary-outline-border"],
  },
  {
    name: "dark-blue-961",
    family: "dark-blue",
    hex: "#114870",
    figma: "Second/Dark blue colors/Dark blue 961",
    usedBy: ["btn-secondary-black-bg-hover", "chips-dark-bg-hover"],
  },
  {
    name: "dark-blue-1412",
    family: "dark-blue",
    hex: "#012F42",
    figma: "Second/Dark blue colors/Dark blue 1412",
    usedBy: ["btn-secondary-black-bg", "calendar-selected-bg", "steps-fade-arrow-bg", "chips-dark-bg", "button-menu-black-bg", "switcher-active-black-bg"],
  },
  {
    name: "green-107",
    family: "green",
    hex: "#F3F9E6",
    figma: null,
    usedBy: [],
  },
  {
    name: "green-123",
    family: "green",
    hex: "#D9F0AB",
    figma: null,
    usedBy: [],
  },
  {
    name: "green-137",
    family: "green",
    hex: "#C4E88B",
    figma: null,
    usedBy: [],
  },
  {
    name: "green-223",
    family: "green",
    hex: "#82BF00",
    figma: null,
    usedBy: [],
  },
  {
    name: "green-289",
    family: "green",
    hex: "#72A716",
    figma: null,
    usedBy: [],
  },
  {
    name: "green-333",
    family: "green",
    hex: "#699B12",
    figma: null,
    usedBy: [],
  },
  {
    name: "grey-106",
    family: "grey",
    hex: "#F8F8F8",
    figma: "Second/Grey colors/Grey 106",
    usedBy: ["menu-item-bg-highlighted", "file-upload-bg-hover", "file-item-icon-bg", "card-bg", "steps-fade-bg", "badge-light-grey-bg", "event-file-bg", "informer-bg-grey", "notification-bg-hover", "tag-grey-secondary-bg", "filter-white-bg-hover", "filter-grey-bg-hover", "header-menu-toggle-hover-bg", "header-menu-group-bg", "switcher-grey-bg", "empty-search-icon-bg", "error-page-bg", "item-thumbnail-bg", "autocomplete-highlighted-bg", "mail-feed-used-bg"],
  },
  {
    name: "grey-109",
    family: "grey",
    hex: "#F4F4F4",
    figma: "Second/Grey colors/Grey 109",
    usedBy: ["btn-secondary-grey-bg", "otp-close-bg", "calendar-range-bg", "accordion-card-bg", "chips-light-bg", "chips-disabled-bg", "filter-grey-bg", "filter-disabled-bg", "nav-sidebar-item-active-bg", "header-menu-tile-bg", "switcher-active-bg-on-white", "status-screen-neutral-bg", "scrollbar-track-bg"],
  },
  {
    name: "grey-114",
    family: "grey",
    hex: "#EFEFEF",
    figma: "Second/Grey colors/Grey 114",
    usedBy: ["btn-secondary-grey-bg-hover", "btn-secondary-white-bg-hover", "btn-secondary-outline-bg-hover", "btn-muted-bg", "input-bg-disabled", "select-bg-disabled", "checkbox-disabled-bg", "radio-disabled-bg", "toggle-track-bg-disabled", "range-input-bg-disabled", "accordion-card-bg-hover", "card-bg-hover", "notification-bg-pressed", "toast-information-bg", "chips-light-bg-hover", "button-menu-border", "nav-sidebar-item-hover-bg", "header-item-hover-bg", "switcher-hover-bg", "nps-card-border", "item-hover-bg", "table-row-hover-bg", "table-row-added-bg", "shimmer-via"],
  },
  {
    name: "grey-124",
    family: "grey",
    hex: "#E6E6E6",
    figma: "Second/Grey colors/Grey 124",
    usedBy: ["btn-secondary-grey-bg-active", "btn-secondary-white-bg-active", "btn-secondary-outline-bg-active", "progress-track-bg", "badge-disabled-light-grey-bg", "table-row-active-bg"],
  },
  {
    name: "grey-134",
    family: "grey",
    hex: "#DEDEDE",
    figma: "Second/Grey colors/Grey 134",
    usedBy: ["divider", "modal-divider", "menu-item-divider", "calendar-divider", "accordion-card-divider", "accordion-list-border", "accordion-list-divider", "event-connector", "notification-divider", "toast-information-border", "tag-white-border", "tag-grey-info-bg", "nav-sidebar-border", "header-border", "header-divider", "tabs-border", "nps-star-empty-fg", "pagination-border", "item-divider", "ifield-divider", "table-divider", "shimmer-from"],
  },
  {
    name: "grey-166",
    family: "grey",
    hex: "#C8C8CB",
    figma: "Second/Grey colors/Grey 166",
    usedBy: ["btn-muted-fg", "btn-muted-border", "input-border", "input-border-disabled", "input-fg-disabled", "calendar-disabled-fg", "select-border", "select-border-disabled", "select-fg-disabled", "checkbox-border", "checkbox-disabled-border", "checkbox-disabled-fg", "checkbox-caption-fg-disabled", "radio-border", "radio-disabled-border", "radio-disabled-dot", "radio-caption-fg-disabled", "toggle-track-bg-hover", "toggle-caption-fg-disabled", "range-input-border", "range-input-border-disabled", "range-input-track-bg", "range-input-accent-disabled", "file-upload-border-disabled", "file-upload-fg-disabled", "file-upload-subtitle-fg-disabled", "file-item-fg-disabled", "progress-step-hatch", "badge-disabled-light-grey-fg", "button-menu-black-muted-fg", "chips-disabled-fg", "filter-disabled-fg", "header-menu-star-fg", "tabs-fg-disabled", "switcher-border", "switcher-disabled-fg", "error-page-code-fg", "item-value-fg-disabled", "table-summary-divider", "scrollbar-thumb-bg"],
  },
  {
    name: "grey-284",
    family: "grey",
    hex: "#999999",
    figma: "Second/Grey colors/Grey 284",
    usedBy: ["input-border-hover", "input-label-fg", "input-caption-fg", "textarea-icon-fg-disabled", "otp-placeholder-fg", "otp-underline", "menu-item-description-fg", "calendar-muted-fg", "select-border-hover", "select-label-fg", "select-caption-fg", "checkbox-label-fg-disabled", "checkbox-caption-fg", "radio-label-fg-disabled", "radio-caption-fg", "toggle-track-bg", "toggle-label-fg-disabled", "toggle-caption-fg", "range-input-border-hover", "range-input-label-fg", "range-input-scale-fg", "range-input-caption-fg", "file-upload-border", "file-upload-border-hover", "file-upload-subtitle-fg", "file-item-meta-fg", "accordion-list-subtitle-fg", "accordion-list-description-information-fg", "card-meta-fg", "progress-meta-fg", "steps-status-fg", "steps-disabled-fg", "badge-light-grey-fg", "badge-disabled-bg", "event-meta-fg", "informer-meta-fg", "informer-icon-grey", "notification-timestamp-fg", "toast-information-icon", "tag-grey-bg", "chips-subtitle-fg", "nav-sidebar-label-fg", "header-meta-fg", "empty-search-description-fg", "nps-subtitle-fg", "pagination-caption-fg", "pagination-disabled-fg", "item-icon-fg", "item-comment-grey-fg", "ifield-label-fg", "ifield-subtext-fg", "ifield-icon-fg", "ifield-information-fg", "ifield-copy-fg", "autocomplete-subtitle-fg", "table-description-fg", "title-muted-fg", "mail-feed-meta-fg"],
  },
  {
    name: "grey-493",
    family: "grey",
    hex: "#6E7170",
    figma: null,
    usedBy: ["btn-secondary-logo-grey-bg-active"],
  },
  {
    name: "grey-517",
    family: "grey",
    hex: "#6D6D6D",
    figma: "Second/Grey colors/Grey 517",
    usedBy: ["textarea-border-hover", "textarea-fg-disabled", "otp-subtitle-fg", "range-input-value-fg-disabled", "accordion-card-subtitle-fg", "steps-tooltip-bg", "tooltip-bg", "badge-dark-grey-bg", "event-author-fg", "notification-meta-fg", "toast-description-fg", "tabs-fg", "tabs-underline-hover", "switcher-fg-inactive", "nps-close-fg", "ifield-copy-fg-hover", "status-screen-subtitle-fg", "status-screen-neutral-fg", "title-description-fg"],
  },
  {
    name: "grey-645",
    family: "grey",
    hex: "#5C5F5E",
    figma: null,
    usedBy: ["btn-secondary-logo-grey-bg-hover"],
  },
  {
    name: "grey-868",
    family: "grey",
    hex: "#494C4B",
    figma: "Second/Grey colors/Grey 868",
    usedBy: ["btn-secondary-logo-grey-bg", "informer-description-fg", "header-menu-group-fg"],
  },
  {
    name: "grey-873",
    family: "grey",
    hex: "#4A4B4D",
    figma: null,
    usedBy: [],
  },
  {
    name: "grey-1156",
    family: "grey",
    hex: "#38393B",
    figma: null,
    usedBy: [],
  },
  {
    name: "grey-1514",
    family: "grey",
    hex: "#252628",
    figma: "Second/Grey colors/Grey 1514",
    usedBy: ["btn-primary-fg", "btn-secondary-grey-fg", "btn-secondary-white-fg", "btn-secondary-outline-fg", "input-fg", "input-icon-fg", "otp-fg", "otp-close-fg", "otp-title-fg", "modal-title-fg", "menu-item-fg", "calendar-fg", "select-fg", "select-icon-fg", "checkbox-border-hover", "checkbox-checked-fg", "checkbox-label-fg", "radio-border-hover", "radio-checked-dot", "radio-label-fg", "toggle-label-fg", "range-input-value-fg", "range-input-thumb-icon-fg", "file-upload-fg", "file-item-fg", "file-item-icon-fg", "accordion-card-title-fg", "accordion-card-icon-fg", "accordion-list-title-fg", "accordion-list-icon-fg", "accordion-list-description-default-fg", "card-title-fg", "card-thumb-bg", "progress-title-fg", "steps-title-fg", "badge-black-bg", "event-title-fg", "informer-title-fg", "notification-title-fg", "toast-title-fg", "top-fixed-message-title-fg", "top-fixed-message-close-fg", "tag-grey-secondary-fg", "tag-black-bg", "tag-white-fg", "tag-grey-info-fg", "chips-fg", "filter-fg", "filter-icon-fg", "nav-sidebar-fg", "nav-sidebar-icon-fg", "header-fg", "header-icon-fg", "tabs-fg-active", "tabs-underline-active", "switcher-fg", "empty-search-icon-fg", "empty-search-title-fg", "nps-title-fg", "error-page-title-fg", "error-page-description-fg", "pagination-fg", "item-value-fg", "item-thumbnail-fg", "ifield-value-fg", "status-screen-title-fg", "autocomplete-title-fg", "table-fg", "title-fg", "mail-feed-fg"],
  },
  {
    name: "grey-1593",
    family: "grey",
    hex: "#1E2321",
    figma: null,
    usedBy: ["modal-backdrop"],
  },
  {
    name: "lavender-116",
    family: "lavender",
    hex: "#EBECFF",
    figma: "Second/Lavender colors/Lavender 116",
    usedBy: ["menu-banner-lilac-glow"],
  },
  {
    name: "lavender-135",
    family: "lavender",
    hex: "#D9DBFF",
    figma: "Second/Lavender colors/Lavender 135",
    usedBy: ["menu-banner-lilac-bg"],
  },
  {
    name: "mint-107",
    family: "mint",
    hex: "#E5FCF1",
    figma: "Second/Mint colors/Mint 107",
    usedBy: ["tag-green-secondary-bg"],
  },
  {
    name: "mint-110",
    family: "mint",
    hex: "#E7F8F0",
    figma: null,
    usedBy: ["status-screen-success-bg"],
  },
  {
    name: "mint-119",
    family: "mint",
    hex: "#BDF8DB",
    figma: "Second/Mint colors/Mint 119",
    usedBy: ["toast-checked-bg", "menu-banner-green-glow"],
  },
  {
    name: "mint-135",
    family: "mint",
    hex: "#89F2BD",
    figma: "Second/Mint colors/Mint 135",
    usedBy: ["toast-checked-border", "menu-banner-green-bg"],
  },
  {
    name: "mint-230",
    family: "mint",
    hex: "#39C182",
    figma: "Status/Mint 230",
    usedBy: ["accordion-list-description-success-fg", "progress-green", "event-status-success-bg", "informer-icon-green", "toast-checked-icon", "tag-green-bg", "item-right-text-fg", "ifield-success-fg", "table-number-positive-fg"],
  },
  {
    name: "mint-396",
    family: "mint",
    hex: "#1F9254",
    figma: null,
    usedBy: ["status-screen-success-fg"],
  },
  {
    name: "red-110",
    family: "red",
    hex: "#FFF0F0",
    figma: "Second/Red colors/Red 110",
    usedBy: ["file-item-error-bg", "accordion-card-blocked-bg", "tag-red-secondary-bg"],
  },
  {
    name: "red-117",
    family: "red",
    hex: "#FFE8E3",
    figma: "Second/Red colors/Red 117",
    usedBy: ["accordion-card-blocked-bg-hover", "toast-error-bg", "top-fixed-message-red-bg", "mail-feed-error-bg"],
  },
  {
    name: "red-147",
    family: "red",
    hex: "#FFBEB5",
    figma: "Second/Red colors/Red 147",
    usedBy: ["toast-error-border"],
  },
  {
    name: "red-182",
    family: "red",
    hex: "#FF737D",
    figma: "Second/Red colors/Red 182",
    usedBy: ["btn-destructive-bg-active"],
  },
  {
    name: "red-344",
    family: "red",
    hex: "#F0535E",
    figma: "Second/Red colors/Red 344",
    usedBy: ["btn-destructive-bg-hover", "input-border-error-hover", "select-border-error-hover"],
  },
  {
    name: "red-410",
    family: "red",
    hex: "#DE4A2A",
    figma: null,
    usedBy: [],
  },
  {
    name: "red-418",
    family: "red",
    hex: "#D74B54",
    figma: "Status/Red 418",
    usedBy: ["btn-destructive-bg", "input-border-error", "input-caption-error-fg", "otp-error-fg", "select-border-error", "select-caption-error-fg", "checkbox-border-error", "checkbox-caption-error-fg", "radio-border-error", "radio-caption-error-fg", "toggle-caption-error-fg", "range-input-accent-error", "range-input-caption-error-fg", "file-upload-border-error", "file-item-error-fg", "accordion-list-description-error-fg", "progress-red", "steps-status-error-fg", "badge-red-bg", "informer-icon-red", "notification-dot", "toast-error-icon", "top-fixed-message-red-icon", "tag-red-bg", "header-logout-fg", "header-unread-dot", "item-comment-red-fg", "ifield-error-fg", "status-screen-error-fg"],
  },
  {
    name: "red-488",
    family: "red",
    hex: "#CB4022",
    figma: null,
    usedBy: [],
  },
  {
    name: "red-603",
    family: "red",
    hex: "#B92F10",
    figma: null,
    usedBy: [],
  },
  {
    name: "red-117-alt",
    family: "red-117-alt",
    hex: "#FAE9EA",
    figma: null,
    usedBy: ["status-screen-error-bg"],
  },
  {
    name: "red-147-alt",
    family: "red-147-alt",
    hex: "#FFC9B5",
    figma: null,
    usedBy: [],
  },
  {
    name: "red-182-alt",
    family: "red-182-alt",
    hex: "#FFAB99",
    figma: null,
    usedBy: [],
  },
  {
    name: "white-101",
    family: "white",
    hex: "#FFFFFF",
    figma: "Second/Grey colors/White 101",
    usedBy: ["btn-secondary-black-fg", "btn-secondary-white-bg", "btn-secondary-outline-bg", "btn-destructive-fg", "btn-secondary-logo-grey-fg", "input-bg", "modal-bg", "calendar-selected-fg", "select-bg", "checkbox-bg", "radio-bg", "toggle-thumb-bg", "range-input-bg", "range-input-thumb-icon-fg-error", "range-input-thumb-icon-fg-disabled", "file-upload-bg", "file-upload-bg-disabled", "card-thumb-fg", "steps-bg", "steps-tooltip-fg", "tooltip-fg", "badge-red-fg", "badge-contra-red-border", "badge-dark-grey-fg", "badge-black-fg", "badge-disabled-fg", "informer-bg-white", "notification-bg", "tag-green-fg", "tag-orange-fg", "tag-red-fg", "tag-blue-fg", "tag-grey-fg", "tag-black-fg", "tag-white-bg", "button-menu-black-fg", "button-menu-bg", "chips-dark-fg", "filter-white-bg", "nav-sidebar-bg", "header-bg", "header-menu-tile-icon-bg", "switcher-white-bg", "switcher-active-bg", "switcher-active-black-fg", "nps-card-bg", "table-bg", "mail-feed-default-bg"],
  },
  {
    name: "yellow-104",
    family: "yellow",
    hex: "#FFFAE0",
    figma: "Second/Yellow colors/Yellow 104",
    usedBy: ["tag-orange-secondary-bg"],
  },
  {
    name: "yellow-114",
    family: "yellow",
    hex: "#FDF0C1",
    figma: "Second/Yellow colors/Yellow 114",
    usedBy: ["toast-attention-bg", "status-screen-attention-bg"],
  },
  {
    name: "yellow-134",
    family: "yellow",
    hex: "#FADC89",
    figma: "Second/Yellow colors/Yellow 134",
    usedBy: ["toast-attention-border"],
  },
  {
    name: "yellow-167",
    family: "yellow",
    hex: "#F8C000",
    figma: null,
    usedBy: ["nps-star-fg"],
  },
  {
    name: "yellow-214",
    family: "yellow",
    hex: "#EEA20F",
    figma: "Status/Yellow 214",
    usedBy: ["loader-warning-fg", "accordion-list-description-attention-fg", "progress-amber", "event-status-attention-bg", "informer-icon-yellow", "toast-attention-icon", "tag-orange-bg", "ifield-attention-fg"],
  },
  {
    name: "yellow-400",
    family: "yellow",
    hex: "#B76E00",
    figma: null,
    usedBy: ["item-comment-yellow-fg", "status-screen-attention-fg"],
  },
]
